version: "2.3"
services:
    gen-model:
        image: chatai:latest
        runtime: nvidia
        volumes:
            - ./checkpoints:/checkpoints
            - ./models:/models/
            - ./input.txt:/input.txt
        command: "--genmodel"

    run-bot:
        image: chatai:latest
        runtime: nvidia
        volumes:
            - ./checkpoints:/checkpoints
            - ./models:/models/
        environment:
            - DISCORD_TOKEN=${TOKEN}
